services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=RockStrong@Passw0rd
    volumes:
      - ./sql-volume:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: unless-stopped
